### ISSUE TITLE
Metropolis coupled MCMC (MCMCMC)

### ISSUE THREAD

**Issue by PhyloStar** [PhyloStar/CyBayes#26]
The next step is to implement MCMCMC for sampling trees. The process essentially consists of a cold chain and 2<= **n** <= N hot chains whose exponent is set to 1/(1+alpha*(n-1)) and alpha is 0.1. 

Briefly, there will be an exchange of states between two chains once in a while following an acceptance ratio given here:
http://bamm-project.org/mc3.html

The question is how to exchange states. Essentially, this is parallel simulated annealing. @robertostling any thoughts about this. I don't have much experience with MPI programming. May be there is simpler way to achieve this.

**Comment by robertostling** [comment]
Interesting approach, I wasn't aware of this. It was a long time since I used MPI so I don't have the API in memory, but wouldn't it make sense to have a shared pool (updated asynchronously) of likelihood values updated every now and then by the worker threads, then each worker can just every now and then randomly pick another thread, compare its most recent likelihood and sample the swap decision, and then inform the other thread of this decision. That thread would then have to throw away its current state, and synchronously exchange the saved states (or exchange temperatures---I guess the states never have to be copied  between threads) that the likelihood value refers to with the first thread.

At least I think the likelihood and temperature is the only thing that needs to be communicated between threads, or am I wrong here?

**Comment by robertostling** [comment]
Interesting approach, I wasn't aware of this. It was a long time since I used MPI so I don't have the API in memory, but wouldn't it make sense to have a shared pool (updated asynchronously) of likelihood values updated every now and then by the worker threads, then each worker can just every now and then randomly pick another thread, compare its most recent likelihood and sample the swap decision, and then inform the other thread of this decision. That thread would then have to throw away its current state, and synchronously exchange the saved states (or exchange temperatures---I guess the states never have to be copied  between threads) that the likelihood value refers to with the first thread.

At least I think the likelihood and temperature is the only thing that needs to be communicated between threads, or am I wrong here?

**Comment by PhyloStar** [comment]
Okay,  the idea sounds great. A tree data structure and some parameter vectors have to be exchanged between chains. 

I think the states have to be copied between threads. Can the threads approach be used then?

**Comment by robertostling** [comment]
Sure, as long as the serialization/copying overhead doesn't start to dominate, but I guess that won't be a problem here.

But why would you need to copy states? Wouldn't exchanging temperatures be equivalent to exchanging states?

**Comment by PhyloStar** [comment]
Quite true. In such case, a pointer to the cold chain is required to sample states.

**Comment by PhyloStar** [comment]
@robertostling Can you help me with writing some code that can exchange this parameters? Everything is in Python3, I can integrate the code into the program? I intend to submit a demo paper to EMNLP or some other CL venue using this software with some testsets where we have gold standard trees to evaluate the program against. In that case, I will add you as a co-author to the paper. What do you think?

**Comment by robertostling** [comment]
I can have a look, which code is this? And how many chains are you planning to run? I'm wondering if MPI is necessary (never tried its Python interface), or if it is enough with Python's standard multiprocessing functionality.

**Comment by PhyloStar** [comment]
https://github.com/PhyloStar/CyBayes/blob/master/mat_mcmc_gamma.py is the main file which performs MCMC.

This program calls the Metropolis-Hastings ratio. This program should be called n times.

Standard multiprocessing functionality is sufficient I think since that would be close to what you suggested.

I am thinking of 4 chains but that should be set from command line.  1 chain is cold and the rest are hot. I want to set the temperature to 1+(C(n-1))  where C=0.1 and n is the chain number.

n=1 shows the cold chain. Like you told only the temperatures of the chains can be exchanged.

Only the cold chains states are sampled and printed to the file.

**Comment by PhyloStar** [comment]
Added simulated tempering solution from Geyer 2011 (Handbook of MCMC). Works fine and is quite fast.
